
package com.guy.guysstore;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestServiceService", targetNamespace = "http://guysstore.guy.com/", wsdlLocation = "http://localhost:8080/GuysStore-1.0-SNAPSHOT/testsoap?wsdl")
public class TestServiceService
    extends Service
{

    private final static URL TESTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSERVICESERVICE_EXCEPTION;
    private final static QName TESTSERVICESERVICE_QNAME = new QName("http://guysstore.guy.com/", "TestServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GuysStore-1.0-SNAPSHOT/testsoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSERVICESERVICE_WSDL_LOCATION = url;
        TESTSERVICESERVICE_EXCEPTION = e;
    }

    public TestServiceService() {
        super(__getWsdlLocation(), TESTSERVICESERVICE_QNAME);
    }

    public TestServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSERVICESERVICE_QNAME, features);
    }

    public TestServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTSERVICESERVICE_QNAME);
    }

    public TestServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSERVICESERVICE_QNAME, features);
    }

    public TestServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServicePort")
    public TestService getTestServicePort() {
        return super.getPort(new QName("http://guysstore.guy.com/", "TestServicePort"), TestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServicePort")
    public TestService getTestServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://guysstore.guy.com/", "TestServicePort"), TestService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSERVICESERVICE_EXCEPTION!= null) {
            throw TESTSERVICESERVICE_EXCEPTION;
        }
        return TESTSERVICESERVICE_WSDL_LOCATION;
    }

}
