
package com.guy.guysstore;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestService", targetNamespace = "http://guysstore.guy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://guysstore.guy.com/", className = "com.guy.guysstore.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://guysstore.guy.com/", className = "com.guy.guysstore.HelloResponse")
    @Action(input = "http://guysstore.guy.com/TestService/helloRequest", output = "http://guysstore.guy.com/TestService/helloResponse")
    public String hello();

}
